// Generated by Wrangler by running `wrangler types`

interface Env {
	OMNI_CACHE: KVNamespace;
	OMNI_KEYS: KVNamespace;
	DEFAULT_ROUTING_STRATEGY: "priority";
	DEFAULT_OUTPUT_STYLE: "none";
	SEARXNG_URL: "";
	ENABLE_MODALITY_BRIDGE: "true";
	ENABLE_CONTEXT_COMPRESSION: "true";
	ENABLE_JINA_READER: "true";
	ENABLE_MCP_SERVER: "true";
	ENABLE_QUOTA_SHARING: "true";
	MAX_RETRIES: "3";
	RETRY_DELAY_MS: "1000";
	AI: Ai;
}
