import type { ProviderConfig } from "@/types/provider";

export const PROVIDER_REGISTRY: Record<string, ProviderConfig> = {
  // --- Provedores Oficiais & Cloud Empresariais ---
  openai: {
    id: "openai",
    name: "OpenAI Oficial",
    baseUrl: "https://api.openai.com/v1",
    authType: "bearer",
    models: [
      "gpt-4o",
      "gpt-4o-mini",
      "o1",
      "o1-mini",
      "o3-mini",
      "chatgpt-4o-latest",
      "gpt-4-turbo",
    ],
    freeTier: false,
    costPerMillionInput: 2.5,
    costPerMillionOutput: 10.0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  azure: {
    id: "azure",
    name: "Azure OpenAI Service",
    baseUrl: "https://openai.azure.com",
    authType: "apikey-header",
    headerName: "api-key",
    models: ["azure/gpt-4o", "azure/gpt-4o-mini"],
    freeTier: false,
    costPerMillionInput: 2.5,
    costPerMillionOutput: 10.0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  bedrock: {
    id: "bedrock",
    name: "Amazon Bedrock",
    baseUrl: "https://bedrock-runtime.us-east-1.amazonaws.com",
    authType: "bearer",
    models: [
      "anthropic.claude-3-5-sonnet-20241022-v2:0",
      "meta.llama3-70b-instruct-v1:0",
    ],
    freeTier: false,
    costPerMillionInput: 3.0,
    costPerMillionOutput: 15.0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  alibaba: {
    id: "alibaba",
    name: "Alibaba Cloud (DashScope / Qwen)",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    authType: "bearer",
    models: [
      "qwen-max",
      "qwen-plus",
      "qwen-turbo",
      "qwen2.5-coder-32b-instruct",
      "qwen2.5-72b-instruct",
    ],
    freeTier: true,
    costPerMillionInput: 0.2,
    costPerMillionOutput: 0.6,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },

  // --- Provedores Gratuitos de Alta Capacidade & Agregadores ---
  gemini: {
    id: "gemini",
    name: "Google Gemini (AI Studio)",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    authType: "query",
    models: ["gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash", "gemini-2.5-pro"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
    rpmLimit: 15,
  },
  antigravity: {
    id: "antigravity",
    name: "Antigravity CLI (Google Cloud Code Assist)",
    baseUrl: "https://cloudcode-pa.googleapis.com",
    authType: "oauth",
    models: ["gemini-2.5-pro", "gemini-2.5-flash", "claude-3-7-sonnet"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  groq: {
    id: "groq",
    name: "Groq Cloud",
    baseUrl: "https://api.groq.com/openai/v1",
    authType: "bearer",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "mixtral-8x7b-32768"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    rpmLimit: 30,
  },
  cerebras: {
    id: "cerebras",
    name: "Cerebras Inference",
    baseUrl: "https://api.cerebras.ai/v1",
    authType: "bearer",
    models: ["llama3.3-70b", "llama3.1-8b"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
    rpmLimit: 30,
  },
  "cloudflare-ai": {
    id: "cloudflare-ai",
    name: "Cloudflare Workers AI (Nativo)",
    authType: "native-binding",
    models: [
      "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
      "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
      "@cf/qwen/qwen2.5-coder-32b-instruct",
      "@cf/meta/llama-3.2-3b-instruct",
    ],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  "1min": {
    id: "1min",
    name: "1min.ai (com ReAct Tool Calling)",
    baseUrl: "https://api.1min.ai/api/chat-with-ai",
    authType: "apikey-header",
    headerName: "API-KEY",
    models: ["1min/gpt-4o", "1min/claude-3-5-sonnet", "1min/gemini-2.0-flash"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: true,
  },
  freeapikey: {
    id: "freeapikey",
    name: "FreeAPIKey (Agregador)",
    baseUrl: "https://api.freeapikey.com/v1",
    authType: "bearer",
    models: ["gpt-4o-mini", "claude-3-haiku", "gemini-flash"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  pollinations: {
    id: "pollinations",
    name: "Pollinations.ai (Ilimitado / Keyless)",
    baseUrl: "https://text.pollinations.ai/openai",
    authType: "bearer",
    models: ["openai", "mistral", "claude", "karma"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: false,
    supportsVision: false,
  },
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    authType: "bearer",
    models: [
      "meta-llama/llama-3.3-70b-instruct:free",
      "deepseek/deepseek-r1:free",
      "google/gemini-2.0-flash-exp:free",
    ],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: true,
  },
  sambanova: {
    id: "sambanova",
    name: "SambaNova Systems",
    baseUrl: "https://api.sambanova.ai/v1",
    authType: "bearer",
    models: ["Meta-Llama-3.3-70B-Instruct", "Qwen2.5-72B-Instruct"],
    freeTier: true,
    costPerMillionInput: 0,
    costPerMillionOutput: 0,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    authType: "bearer",
    models: ["mistral-small-latest", "codestral-latest"],
    freeTier: true,
    costPerMillionInput: 0.2,
    costPerMillionOutput: 0.6,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek API",
    baseUrl: "https://api.deepseek.com/v1",
    authType: "bearer",
    models: ["deepseek-chat", "deepseek-reasoner"],
    freeTier: false,
    costPerMillionInput: 0.14,
    costPerMillionOutput: 0.28,
    supportsStreaming: true,
    supportsTools: true,
    supportsVision: false,
  },
};



// Registry mutável para provedores customizados registrados via painel admin
export const CUSTOM_PROVIDER_REGISTRY: Record<string, ProviderConfig> = {};

export function registerCustomProvider(id: string, cfg: Partial<ProviderConfig> & { baseUrl: string }): void {
  CUSTOM_PROVIDER_REGISTRY[id] = {
    id,
    name: cfg.name || id,
    baseUrl: cfg.baseUrl,
    authType: cfg.authType || "bearer",
    headerName: cfg.headerName,
    models: cfg.models || [],
    freeTier: cfg.freeTier ?? true,
    costPerMillionInput: cfg.costPerMillionInput ?? 0,
    costPerMillionOutput: cfg.costPerMillionOutput ?? 0,
    supportsStreaming: cfg.supportsStreaming ?? true,
    supportsTools: cfg.supportsTools ?? true,
    supportsVision: cfg.supportsVision ?? false,
  } as ProviderConfig;
}

export function getProviderConfig(id: string): ProviderConfig | undefined {
  return PROVIDER_REGISTRY[id] || CUSTOM_PROVIDER_REGISTRY[id];
}
